# Generated by Django 3.1.2 on 2020-10-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_travels_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Places_visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(verbose_name='date to go on trip')),
                ('end_date', models.DateTimeField(verbose_name='date I ended the trip')),
                ('links_sharing', models.URLField(max_length=500)),
                ('summury', models.TextField(blank=True)),
                ('my_travels_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_trip_stories.my_travels_plan')),
            ],
        ),
    ]
