# Generated by Django 3.1.2 on 2020-10-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_travels_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Places_visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('my_travels_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_trip_stories.my_travels_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField()),
                ('title_trip', models.CharField(max_length=200)),
                ('Places_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_trip_stories.places_visited')),
            ],
        ),
    ]
